// GENERATED by build/build_site.py from boss_config.json. Do not edit; run ./set_ca.sh <CA> to change the CA.
window.BOSS_CONFIG={
 "ca": "4AcmBHJaSqJCDT99W769ecEXupsj7mkr2Wdfien2pump",
 "pump_url": "https://pump.fun/coin/4AcmBHJaSqJCDT99W769ecEXupsj7mkr2Wdfien2pump",
 "x_url": "https://x.com/TheBossCoin_SOL",
 "ranked_url": "https://boss-runner-fto6.onrender.com/",
 "round_start_ms": 1790902800000,
 "round_ms": 259200000,
 "round_days": 3,
 "tries_per_round": 3,
 "sell_limit_pct_per_day": 1.0,
 "sell_limit_wallets": {
  "dev": null,
  "pot": null
 },
 "prize": {
  "from_round": 2,
  "pot_pct_of_round_fees": 20,
  "sponsor_pct": 80,
  "top_n": 5,
  "split": [
   40,
   25,
   15,
   12,
   8
  ],
  "min_pot_sol": 0.05,
  "rollover": true
 },
 "lifetime_prize_cap_usd": null,
 "whale_flag_pct": 2.0,
 "skins": [
  {
   "name": "Gold Rush Crown",
   "price_tokens": 50000
  },
  {
   "name": "Toxic Green Crown",
   "price_tokens": 50000
  },
  {
   "name": "Buckeye Red Crown",
   "price_tokens": 100000
  },
  {
   "name": "Void Crown",
   "price_tokens": 250000
  }
 ],
 "skins_network": "devnet (test only)"
};
