// GENERATED by build/build_site.py from boss_config.json. Do not edit; run ./set_ca.sh <CA> to change the CA.
window.BOSS_CONFIG={
 "ca": "4AcmBHJaSqJCDT99W769ecEXupsj7mkr2Wdfien2pump",
 "pump_url": "https://pump.fun/coin/4AcmBHJaSqJCDT99W769ecEXupsj7mkr2Wdfien2pump",
 "x_url": "https://x.com/TheBossCoin_SOL",
 "ranked_url": "https://boss-runner-fto6.onrender.com/",
 "round_start_ms": 1790902800000,
 "round_ms": 259200000,
 "round_days": 3,
 "tries_per_round": 3,
 "sell_limit_pct_per_day": 1.0,
 "sell_limit_wallets": {
  "dev": null,
  "pot": null
 },
 "split_pct": {
  "prize": 50,
  "reserve": 40,
  "ops": 10
 },
 "top_split": [
  25,
  18,
  13,
  10,
  8,
  7,
  6,
  5,
  4,
  4
 ],
 "tiers": [
  {
   "name": "T1 <$100K",
   "pot_cap_usd": 100,
   "winner_cap_usd": 20
  },
  {
   "name": "T2 $100K-500K",
   "pot_cap_usd": 400,
   "winner_cap_usd": 60
  },
  {
   "name": "T3 $500K-2M",
   "pot_cap_usd": 1200,
   "winner_cap_usd": 180
  },
  {
   "name": "T4 >$2M",
   "pot_cap_usd": 3000,
   "winner_cap_usd": 450
  }
 ],
 "lifetime_prize_cap_usd": null,
 "whale_flag_pct": 2.0,
 "skins": [
  {
   "name": "Gold Rush Crown",
   "price_tokens": 50000
  },
  {
   "name": "Toxic Green Crown",
   "price_tokens": 50000
  },
  {
   "name": "Buckeye Red Crown",
   "price_tokens": 100000
  },
  {
   "name": "Void Crown",
   "price_tokens": 250000
  }
 ],
 "skins_network": "devnet (test only)"
};
